### ISSUE TITLE
Hierarchical technological rules

### ISSUE THREAD

**Issue by pruneson46** [pruneson46/DSSEchapter#2]
Can we give an example of a hierarchical technological rule in Section 3.1?

**Comment by pruneson46** [comment]
The example of tool vs algorithm in section 3.3. may perhaps be used?

**Comment by emenlu** [comment]
There are examples in our SLR on regression testing:

> Such rules could be formulated in detail for a single technique (i.e. one row in the mapping, as in example TR1) or with fewer details for a set of techniques (by including only the common denominators for that set, TR2) or in more general terms by selecting nodes at a higher level in the taxonomy (TR3). Three illustrative examples (TR1-3) are given:
TR 1
To reduce the regression test suite and testing time when regression testing large scale software systems utilise the following information attributes: #contributors of a piece of code, measured execution time, verdict, build type, variant under test and link to tested branch from test reports and fix time in issue reports. This example was extracted from an evaluation of a tool called THEO (Herzig et al. 2015).
 TR 2
To increase feature coverage, reduce testing time and improve fault detection capability when regression testing customisable, real-time systems, utilise information about verdicts and execution time in test reports. (This rule is based on the intersection of the classification of two different techniques, Multi-perspective prioritisation (Marijan 2015) and TEMSA (Wang et al. 2015), which have been evaluated in several studies (Marijan et al. 2013; Marijan 2015; Wang et al. 2013a, 2013b, 2014, 2015, 2016, 2017)).
 TR 3
To improve efficiency and effectiveness when regression testing large scale complex systems, utilise information attributes of the test reports. (This rule is a generalisation of TR2 and is supported by the same studies and another two (Ekelund and Engström 2015; Engström et al. 2011).)

**Comment by pruneson46** [comment]
Added text: For example, an abstract rule may recommend using a general type of technology, while several more detailed rules may specify the use of technology, embedded in a specific tool.
