### ISSUE TITLE
Further reading

### ISSUE THREAD

**Issue by pruneson46** [pruneson46/DSSEchapter#6]
Any literature reference to this paragraph?

Purely observational studies, which aim to characterize the status of a field of soft- ware engineering practice, primarily have the characteristic of explanatory sciences as they aim to explore the current, ‘natural’ state of practice. This does not refer to ‘natural’ in the sense of natural sciences, as software and its engineering are designed artifacts. However, the phenomena can be studied with respect to properties that are considered emergent from the phenomena, independently of their design variations. Observational studies, which aim to understand a problem, with the purpose of de- veloping or improving an intervention to address the problem, may be viewed as a part of the design sciences paradigm.

**Comment by emenlu** [comment]
I'm not sure what the message is. Maybe skip it?

**Comment by margaretstorey** [comment]
It isn't clear to me either... I would skip it.

**Comment by pruneson46** [comment]
Done
